### ISSUE TITLE
/find returns empty if using 2 stars until scan-frequency interval passed

### ISSUE THREAD

**Issue by kkopachev** [go-graphite/go-carbon#150]
In freshly started go-carbon, making request with 2 wildcards at the end returns empty result:
```
curl -v 'http://carbon:8080/metrics/find/?format=json&query=carbon.agents.*.*'
* Hostname was NOT found in DNS cache
*   Trying 172.19.0.2...
* Connected to carbon (172.19.0.2) port 8080 (#0)
> GET /metrics/find/?format=json&query=carbon.agents.*.* HTTP/1.1
> User-Agent: curl/7.38.0
> Host: carbon:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< Date: Sat, 25 Mar 2017 05:54:05 GMT
< Content-Length: 28
< 
* Connection #0 to host carbon left intact
{"name":"carbon.agents.*.*"}
```

However, running the same query after `scan-frequency` interval specified in the config under `[carbonserver]` section, returns expected result:
```
curl -v 'http://carbon:8080/metrics/find/?format=json&query=carbon.agents.*.*'
* Hostname was NOT found in DNS cache
*   Trying 172.19.0.2...
* Connected to carbon (172.19.0.2) port 8080 (#0)
> GET /metrics/find/?format=json&query=carbon.agents.*.* HTTP/1.1
> User-Agent: curl/7.38.0
> Host: carbon:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Accept-Encoding
< Date: Sat, 25 Mar 2017 06:01:24 GMT
< Content-Length: 463
< 
* Connection #0 to host carbon left intact
{"name":"carbon.agents.*.*","matches":[{"path":"carbon.agents.22c1408f169d.cache","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.carbonserver","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.persister","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.pickle","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.runtime","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.tcp","isLeaf":false},
{"path":"carbon.agents.22c1408f169d.udp","isLeaf":false}]}
```

Looks like it's related to https://github.com/grobian/carbonserver/issues/13 I'd thought it should fallback to filesystem glob if expression starts or ends with star, regardless of how many stars in the middle, but I'm not sure what was the reasons to make it look only for last star.

**Comment by Civil** [comment]
I'll have a look on that. I'm still not sure if it's better to force trigram index to rebuild or to improve fs-based globs for that case.

**Comment by Civil** [comment]
Can you post the config file? Also what version are you using?

I can't reproduce that with version from master.

**Comment by kkopachev** [comment]
Still reproducible with latest master. 
I created a repo https://github.com/kkopachev/sitespeed.io/tree/go-carbon-metrics with test case.

**Comment by Civil** [comment]
Ok, I was able to reproduce that. That happens only when your data dir is empty.

I think I'll just return "Error 500" in that case.

**Comment by Civil** [comment]
Ok, I've tried to implement a fix, and actually find out that the problem is a little bit different.

When you start go-carbon with carbonserver, it initiates file scan to create the index. As in your case whispder data dir is empty, it creates empty index and that's why when you start sending data it uses empty index to perform find query.

I think in that case the best option will be to fallback to filesystem walk if you have 0 metrics in your index. In that case it will still return original query if your whisper data dir is empty, but I think that's also how graphite-web behave in similar cases.

E.x.
```
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/lomik/go-carbon $ wget -q -O- "http://localhost:8080/metrics/find/?format=json&query=carbon.agents.*.*"
{"name":"carbon.agents.*.*"}
vsmirnov@ml905507 ~/go/gopath_third_party/src/github.com/lomik/go-carbon $ mkdir -p ~/whisper/data/carbon/agents/foo && touch ~/whisper/data/carbon/agents/foo/bar.wsp && wget -q -O- "http://localhost:8080/metrics/find/?format=json&query=carbon.agents.*.*"
{"name":"carbon.agents.*.*","matches":[{"path":"carbon.agents.foo.bar","isLeaf":true}]}
```

**Comment by kkopachev** [comment]
From my understanding carbonserver rebuilds index with period defined in config (`scan-frequency`). General problem is that index contains data about whisper files existed at the scan time. However, it could happen that new metric come in and it will not be discovered until next scan time. 
Maybe on time new metric is created, index should be rebuilt?

**Comment by Civil** [comment]
If you have a lot of data, rebuild will take some time, and it might a matter of minutes for millions of metrics. That's why we don't update it every create. I think it might be possible to keep track of new metrics and also do extra matching on them. But that will take some time to implement.

You can disable trigram index, at this moment it can be done by setting 'scan-interval' to 0. Then all your find queries will do FS-based globbing, like graphite-web. In next group of commits this will be done by a separate switch.

**Comment by kkopachev** [comment]
That sounds good. Then there is nothing to fix. Would be great, however, to put a little not in readme that this is expected behavior. My first impression was that go-carbon was not working at all right after first start.
Thanks a lot for looking into that!

**Comment by Civil** [comment]
https://github.com/lomik/go-carbon/pull/163

This will partly fix that issue. (comments about how to disable trigram index, and it will disable cache for empty resulsts)

**Comment by kkopachev** [comment]
Thank you.
