### ISSUE TITLE
shutdown behavior and carbonlink

### ISSUE THREAD

**Issue by fsperling** [go-graphite/go-carbon#260]
Hi,
I'm currently trying out go-carbon to see whether it can handle 8 million metrics a minute and replace carbon-cache in our setup.

I was wondering if go-carbon writes all metrics to disk that are in the cache on a stop or restart event. 
I had a few million metrics in the cache and the restart was so quick that it seemed they were dropped. Is that correct?

I also have troubles getting the carbonlink working.
In graphite-web I have carbonlink configured with: 127.0.0.1:port:someID
But metrics only show up after they have been written to disk. (currently 2000 seconds :-/)
Any tips for debugging this?

**Comment by azhiltsov** [comment]
In regards of first part of the question, look for [dump] config section. It explained in README.md

**Comment by deniszh** [comment]
If you replacing multiple carbon-caches with single go-carbon? could you please elaborate your migration plan a bit?

**Comment by azhiltsov** [comment]
@fsperling 130K points a second is quite doable with go-carbon, but at such rate you will have to tune the config a bit.
Try to use 
high enough max-size
and
write-strategy=noop

Increase max-cpu to use all or almost all available cores
scale "workers" accordingly (we are using half of max-cpu)
throttle your writes in order to prevent your disk saturation
max-updates-per-second = (we are using 30000 on disks capable to handle up to 100000 write iops)
keep in mind that whisper update causes write/read amplification on archives with many layers.

Follow recommendation on https://github.com/lomik/go-carbon#os-tuning

@deniszh before we migrated to go-carbon we were using many carbon-cache per host with carbon-c-relay on front of them.

**Comment by fsperling** [comment]
Hi,
Thanks for the tip with the dump section.

Currently we have haproxy -> carbon-relay -> carbon-cache
There are 16 carbon-cache processes running.

When I started a go-carbon process I added it to
- the destinations of the carbon-relays
- graphite-web config: `CARBONLINK_HOSTS = ["127.0.0.1:12201:01", "127.0.0.1:12202:02", "127.0.0.1:1220x:0x", ... , "127.0.0.1:20005:17" ]`
With 16 entries for carbon-caches and the last one for go-carbon.
So I had go-carbon and carbon-cache running at the same time. And I slowly increased the amount of metrics that are send to go-carbon.

I imagine that for each query graphite is querying all of the carbonlink hosts as the requested metrics might be split across multiple caches.

The go-carbon config looks like:
```
[carbonlink]
listen = ":20005"
enabled = true
```

**Comment by fsperling** [comment]
@azhiltsov that is really interesting with the read/write amplification.
Is that because whenever I add a new value to a whisper file it has to be checked if older values have to be aggregated and moved around?

Or when I read values across multiple retention periods I have to do a read for each layer/retention?

**Comment by azhiltsov** [comment]
@fsperling 
write amplification happens if you have a multi-layer whisper file. Each write to it requires update of the lower precision archives, if I am reading this right:
https://github.com/go-graphite/go-whisper/blob/73c5cbd69142cbef9bd8ef9c6d485a8d34b4554c/whisper.go#L465
Read amplification has the same root cause. In order to perform the computation you need to read the values.

In regards of your previous comment. I can't comment further as we don't use the python version for a years now, but running go-carbon + [carbonapi](https://github.com/bookingcom/carbonapi) instead

**Comment by fsperling** [comment]
I figured out the problem with the carbonlink.
go-carbon was configured to write statistics to "local" i.e. it put them directly into the go-carbon cache.
The carbonlink config in graphite-web however was looking for the metrcis based on some hashing algo. With tcpdump I could see that for each carbonlink host got queries for different go-carbon metrics that they didnt have.

My solution was to send the go-carbon statistics to the (local) haproxy in front of the relays.

**Comment by deniszh** [comment]
@fsperling : Indeed, it's unfortunately not possible to use go-carbon and normal caches with carbonlink in a same time.
