### ISSUE TITLE
"logger":"slow","message":"Slow Request"

### ISSUE THREAD

**Issue by vedaprasad-j** [go-graphite/go-carbon#295]
I am revamping our legacy graphite cluster, replacing carbon-cache with go-carbon.

The flow is grafana->carbonapi->carbonzipper->go-carbon (carbonserver)

One of your grafana dashboard has around ~150 panels and it takes for ever to load.upon investing all the stacks i see these messages in go-carbon.

{"level":"WARN","timestamp":"2019-06-10T12:27:47.986Z","logger":"slow","message":"Slow Request","time":1.205591778,"url":"/render","referer":""}
{"level":"WARN","timestamp":"2019-06-10T12:27:47.986Z","logger":"slow","message":"Slow Request","time":1.205591778,"url":"/render","referer":""}

is this something to be concerned about ?  Is there something configured wrong on my end?

go-carbon version - 0.14 

Any help would be highly appreciated.

Thanks in advance,
Ved.

**Comment by Civil** [comment]
In current go-carbon there is no logger called "slow", also there is nothing that writes "Slow Request".

Are you sure that you are looking at the go-carbon's logs, and not at the carbonzipper?

In carbonzipper you can encounter such messages if the request will take more than about 1 second. This usually happens when your dashboard have too many data points to fetch (each query have it's own overhead, plus the more data you fetch - the slower it will be) or when some of the backends are slow.

Sometimes you can trade the memory consumption for speed by playing with maxGlobs on carbonzipper side.

**Comment by vedaprasad-j** [comment]
@Civil : Thanks for looking into this, i can confirm the above errors are from carbonapi and not go-carbon. i will close the issue and follow up with carbonapi
